#!/bin/sh

set -e

PGDATA=/db/cluster1
chown postgres:postgres "$PGDATA"

sysrc postgresql_enable="YES"
sysrc postgresql_data="/db/cluster1"

# If the cluster does not exist, run initdb
if ! su postgres -c "pg_ctl status -D $PGDATA" ; then
    su postgres -c "initdb --no-locale -E UTF8 -n -N -D $PGDATA"
    cp /vagrant/pg_hba.conf "$PGDATA/pg_hba.conf"
    cp /vagrant/postgresql.conf "$PGDATA/postgresql.conf"
    chown postgres:postgres "$PGDATA/pg_hba.conf" "$PGDATA/postgresql.conf"
fi

service postgresql start
